Include Security Article in Documentation
lune-org/docs pull request #10
Opened 2024-05-15 10:50 UTC by CompeyDev

As discussed, instead of including a permissions system in lune (https://github.com/lune-org/lune/issues/25), the better alternative would be to educate users instead. 

This PR includes a pure luau sandbox script and a security article explaining what to do with untrusted scripts.

2024-06-17 11:10 UTC, filiptibell requested changes
The security article looks great 👍 but there are several unrelated changes blocking this from getting merged:

- Reformatting of settings / manifest files and driveby changes to versions
- Changes in autogenerated API docs, right now the generator does not work with the new regex apis, I'll take a look and fix it, but it also means the new generated docs are incorrect and must not be published (which would happen automatically on merge)
- Changing the package manager to pnpm for some reason?

If the above changes are reverted and the PR is just the security article I can merge it in

2024-06-17 12:59 UTC, CompeyDev commented
> Reformatting of settings / manifest files and driveby changes to versions

Wasn't aware that they were reformatted, I just bumped the lune version since the sandbox script requires *all* of the standard libraries for the latest version of lune.

> Changing the package manager to pnpm 

I have npm aliases to pnpm since npm gets too slow on large repositories, must've been that.

2024-06-18 06:07 UTC, CompeyDev commented
@filiptibell Could you remove the `.gitattributes` file once this is merged?

2024-06-19 15:50 UTC, filiptibell approved these changes

2024-06-19 15:50 UTC, merged